sudo: false
services:
  - docker

before_install:
  # build docker image with `Dockerfile.dev` config
  - docker build -t lamson/lamson.me -f Dockerfile.dev .

script:
  - docker run lamson/lamson.me yarn ci-check

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "lamson.me"
  env: "Lamsonme-env"
  bucket_name: "elasticbeanstalk-us-east-1-091733176652"
  bucket_path: "lamson.me"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET_KEY"

# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - g++-4.8
#   code_climate:
#     repo_token: ae474865d00b66dab32c385b1799e62a27442b93ea28e655da358d7e0d8587a4
# after_script: 
#   - yarn codeclimate