FROM node:8.14-alpine

WORKDIR /_lamson.me
COPY . .

# Install dependencies
# node_modules/sharp requires `python` and `libvips`...
# See http://sharp.pixelplumbing.com/en/stable/install/#alpine-linux 
#
# --no-cache: download package index on-the-fly, no need to cleanup afterwards
# --virtual: bundle packages, remove whole bundle at once, when done
# See https://github.com/nodejs/docker-node/issues/282#issuecomment-358907790
RUN apk update && apk --no-cache --virtual build-dependencies add python make g++ \
  vips-dev fftw-dev build-base \
  --repository https://alpine.global.ssl.fastly.net/alpine/edge/testing/ \
  --repository https://alpine.global.ssl.fastly.net/alpine/edge/main \
  && yarn install --frozen-lockfile --no-cache \
  && apk del build-dependencies

# Default start command for `docker run ...`
# CMD ...